#!/usr/bin/env bash
# script must accept 2 arguments:
#  	 domain:
#		type: string
#		what: domain name to audit
#		mandatory: yes
#	 subdomain:
#		type: string
#		what: specific subdomain to audit
#		mandatory: no
#Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
print_all() {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1\./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5" }'
}

if [ "$#" -eq 2 ]
then
    print_all "$2.$1" "$2"
else
    print_all "www.$1" "www"
    print_all "lb-01.$1" "lb-01"
    print_all "web-01.$1" "web-01"
    print_all "web-02.$1" "web-02"
fi
