#!/usr/bin/env bash
#transfer a file from our client to a server
#must accepts 4 parameters;
#1-full path of the file 2-IP address 3-username 4- path of SSH

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
IP=$2
user_name=$3
ssh_path=$4

scp -o "StrictHostKeyChecking=no" -i "$ssh_path" "$file_path" "$user_name@$IP:~/"
