#!/usr/bin/env bash
#instructions/commands to install nginx on web server and creating first html
sudo apt-get update
sudo apt-get -y upgrade
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
