#!/bin/env bash
#Configure Nginx that HTTP response contains a custom header
#The name of the custom HTTP header is 'X-Served-By hostname' of the server
custom="add_header X-Served-By $HOSTNAME;"

sudo sed -i "/server_name _/a $custom" /etc/nginx/sites-enabled/default

sudo nginx -t
