#!/usr/bin/env bash
#Installs and configure HAproxy on new lb-01 server.
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Makes sure that HAproxy can be managed via an init script
sudo apt-get update
sudo apt-get -y install haproxy
roundrobin="frontend  frontend_dewa
        bind *:80
        mode http
        default_backend backend_dewa

backend backend_dewa
        balance roundrobin
        server 40896-web-01 54.237.13.137:80 check
        server 40896-web-02 54.87.235.212:80 check"

echo "$roundrobin" | sudo tee -a etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart