#!/usr/bin/env bash
# display 'To infinity and beyond' indefinitely after sleep 2
# display 'I am invincible' when SIGTERM recieved
trap 'echo "I am invincible!!!"; exit' SIGTERM
while [ 1 ]; do
    echo "To infinity and beyond"
    sleep 2
done
