#!/usr/bin/env bash
#this script display 1 to 20 except 4th line "bad luck from china"
#9th line "bad luck from japan", 17th line "bad luck from italy"
count=1
while [ $count -le 20 ]; do
    echo $count
    case $count in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
    esac
    
    count=$((count+1))
done
