#!/usr/bin/env bash
#this script display hours and minutes on each new line
hour=0

while [ $hour -le 12 ]; do
    echo "hour: $hour"
    minute=1
    while [ $minute -le 59 ]; do
	echo $minute
	minute=$((minute+1))
    done

    hour=$((hour+1))
done
